# Numpy Tasks

## Task_1

#### Question 1. Create a numpy array with 6X5 2D array from 10 upwards

In [2]:
import numpy as np

array = np.arange(10,40).reshape(6,5)
array

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

#### Question 2. From question 1, reshape the numpy array to any shape of your choice and return the max value from each column.

In [3]:
array.reshape(3,10).max(axis=0)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

#### Question 3. Create a numpy array A with np.ones with a shape of (3,4). Create another array using the np.arange with a shape of (3,4). 

In [4]:
array1 = np.ones((3,4))
array2 = np.arange(12).reshape(3,4)
array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Question 4. Perform arithmetic operations (+,-,*,/) on the two arrays from question 3.

In [10]:
add = array1 + array2
diff = array1 - array2
prod = array1 * array2
div = array1 / array2

print('The addition of both arrays \n', add)
print('\n+++++++++++++++++++++++++++++++++\n')
print('The difference of both arrays \n', diff)
print('\n+++++++++++++++++++++++++++++++++\n')
print('The product of both arrays \n', prod)
print('\n+++++++++++++++++++++++++++++++++\n')
print('The division of both arrays \n', div)

The addition of both arrays 
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]

+++++++++++++++++++++++++++++++++

The difference of both arrays 
 [[  1.   0.  -1.  -2.]
 [ -3.  -4.  -5.  -6.]
 [ -7.  -8.  -9. -10.]]

+++++++++++++++++++++++++++++++++

The product of both arrays 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

+++++++++++++++++++++++++++++++++

The division of both arrays 
 [[       inf 1.         0.5        0.33333333]
 [0.25       0.2        0.16666667 0.14285714]
 [0.125      0.11111111 0.1        0.09090909]]


C:\Users\user\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


#### Question 5. From question 4, transpose the results of each arithmetic operation.

In [15]:
print('The transpose of the arrays addition \n',   add.T)
print('\n+++++++++++++++++++++++++++++++++\n')
print('The transpose of the arrays difference \n',   diff.T)
print('\n+++++++++++++++++++++++++++++++++\n')
print('The transpose of the arrays multiplication \n',   prod.T)
print('\n+++++++++++++++++++++++++++++++++\n')
print('The transpose of the arrays division \n',  div.T)
print('\n+++++++++++++++++++++++++++++++++\n')

The transpose of the arrays addition 
 [[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]

+++++++++++++++++++++++++++++++++

The transpose of the arrays difference 
 [[  1.  -3.  -7.]
 [  0.  -4.  -8.]
 [ -1.  -5.  -9.]
 [ -2.  -6. -10.]]

+++++++++++++++++++++++++++++++++

The transpose of the arrays multiplication 
 [[ 0.  4.  8.]
 [ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]]

+++++++++++++++++++++++++++++++++

The transpose of the arrays division 
 [[       inf 0.25       0.125     ]
 [1.         0.2        0.11111111]
 [0.5        0.16666667 0.1       ]
 [0.33333333 0.14285714 0.09090909]]

+++++++++++++++++++++++++++++++++

